### ISSUE TITLE
How I can do face recognition?

### ISSUE THREAD

**Issue by datomnurdin** [bharathp666/openAR#4]
As per subject, is it possible to do face recognition using openAR which is comparing it with existing database to check either is it match or not. Please advice. Thank you.

**Comment by bharathp666** [comment]
You can use OpenCV's in-build face recognition methods for your use case. OpenAR is only a subject and does not contain all of OpenCV. More Info -
http://docs.opencv.org/modules/contrib/doc/facerec/facerec_tutorial.html
